### ISSUE TITLE
I can't install the JS dependencies due to an authentication error

### ISSUE THREAD

**Issue by sfermigier** [liqd/adhocracy-plus#1832]
When I run `npm i`, I get an authentication error against the 

```
ghq/github.com/liqd/adhocracy-plus$ npm i
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
...
```

with additional error message in the log:

```
4909 verbose stack HttpErrorAuthUnknown: Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/",service="npm.fontawesome.com"
4909 verbose stack     at /opt/homebrew/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:78:17
4909 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
4909 verbose stack     at async [nodeFromEdge] (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1101:19)
4909 verbose stack     at async [buildDepStep] (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:970:11)
4909 verbose stack     at async Arborist.buildIdealTree (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:216:7)
4909 verbose stack     at async Promise.all (index 1)
4909 verbose stack     at async Arborist.reify (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
4909 verbose stack     at async Install.exec (/opt/homebrew/lib/node_modules/npm/lib/commands/install.js:159:5)
4909 verbose stack     at async module.exports (/opt/homebrew/lib/node_modules/npm/lib/cli.js:78:5)
4910 verbose statusCode 401
4911 verbose pkgid @fortawesome/fontawesome-free@5.15.4
```

**Comment by sfermigier** [comment]
Additionally, with yarn:

```
yarn install v1.22.18
info No lockfile found.
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome%2ffontawesome-free: authentication required".
```

**Comment by Rineee** [comment]
Hello @sfermigier, I hope you could fix the issue! Let us know if you have any further problems installing adhocracy-plus!
