### ISSUE TITLE
Newsletter error in async sending task

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/adhocracy-plus#931]
**URL:** 
**user:** 
**expected behaviour:** Newsletter sends
**behaviour:** There is some error (see below) and the newsletter didn't send.
**important screensize:**
**device & browser:** 
**Comment/Question:** 

```
Traceback (most recent call last):
  File "/home/django/adhocracy-plus/lib/python3.6/site-packages/django/core/mail/message.py", line 62, in forbid_multi_line_headers
    val.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 55: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/django/adhocracy-plus/lib/python3.6/site-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/home/django/adhocracy-plus/lib/python3.6/site-packages/adhocracy4/emails/tasks.py", line 15, in send_async
    return cls().dispatch(object, *args, **kwargs)
  File "/home/django/adhocracy-plus/apps/newsletters/emails.py", line 22, in dispatch
    return super().dispatch(object, *args, **kwargs)
  File "/home/django/adhocracy-plus/lib/python3.6/site-packages/adhocracy4/emails/base.py", line 142, in dispatch
    mail.send()
  File "/home/django/adhocracy-plus/lib/python3.6/site-packages/django/core/mail/message.py", line 291, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/django/adhocracy-plus/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 110, in send_messages
    sent = self._send(message)
  File "/home/django/adhocracy-plus/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 124, in _send
    message = email_message.message()
  File "/home/django/adhocracy-plus/lib/python3.6/site-packages/django/core/mail/message.py", line 259, in message
    self._set_list_header_if_not_empty(msg, 'Reply-To', self.reply_to)
  File "/home/django/adhocracy-plus/lib/python3.6/site-packages/django/core/mail/message.py", line 412, in _set_list_header_if_not_empty
    msg[header] = value
  File "/home/django/adhocracy-plus/lib/python3.6/site-packages/django/core/mail/message.py", line 191, in __setitem__
    name, val = forbid_multi_line_headers(name, val, self.encoding)
  File "/home/django/adhocracy-plus/lib/python3.6/site-packages/django/core/mail/message.py", line 65, in forbid_multi_line_headers
    val = ', '.join(sanitize_address(addr, encoding) for addr in getaddresses((val,)))
  File "/home/django/adhocracy-plus/lib/python3.6/site-packages/django/core/mail/message.py", line 65, in <genexpr>
    val = ', '.join(sanitize_address(addr, encoding) for addr in getaddresses((val,)))
  File "/home/django/adhocracy-plus/lib/python3.6/site-packages/django/core/mail/message.py", line 119, in sanitize_address
    address = Address(nm, addr_spec=addr)
  File "/usr/lib/python3.6/email/headerregistry.py", line 42, in __init__
    a_s, rest = parser.get_addr_spec(addr_spec)
  File "/usr/lib/python3.6/email/_header_value_parser.py", line 1585, in get_addr_spec
    token, value = get_local_part(value)
  File "/usr/lib/python3.6/email/_header_value_parser.py", line 1395, in get_local_part
    if value[0] in CFWS_LEADER:
IndexError: string index out of range
```

**Comment by fuzzylogic2000** [comment]
I tried to send a newsletter locally with the same text, name and subject and it worked fine. I also looked at the users, but there wasn't anything suspicious. (I also tried a username with ü and one with blanks, but the newsletter locally still send.)

```
[["apps.newsletters.emails", "NewsletterEmail", "a4_candy_newsletters", "newsletter", 41, [], {"organisation_pk": 92, "participant_ids": [5766, 7455, 7411, 7346, 7304, 6303, 5769, 5757, 5663, 5652, 5607, 5559, 5554, 2379, 2476, 2473]}], {}]
```

**Comment by fuzzylogic2000** [comment]
It seems to have to do something with the reply-to, but I can't reproduce.
https://sentry.liqd.net/sentry/aplus-prod/issues/1232/
@rmader Can we look at that together?

**Comment by rmader** [comment]
This is super weird. So `val.encode('ascii')` fails because of an `ü` and throws a `UnicodeEncodeError` error - however, the line below should catch it: `except UnicodeEncodeError:`. So there appears to be something wrong with....python? Django? Hmmm...

**Comment by fuzzylogic2000** [comment]
Something wrong with the wörld!

**Comment by rmader** [comment]
Ah, looks like https://code.djangoproject.com/ticket/31784 - fixed in Django 2.2.15

**Comment by rmader** [comment]
So this should be fixed by now.

**Comment by rmader** [comment]
For the record: https://github.com/django/django/commit/1a3835fdf364acb3beebccffbc2aa0c1efe66150
